//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Core.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfraEntities : DbContext
    {
        public InfraEntities()
            : base("name=InfraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLICATIONS> APPLICATIONS { get; set; }
        public virtual DbSet<PERMISSIONS> PERMISSIONS { get; set; }
        public virtual DbSet<PERMISSIONSOFROLE> PERMISSIONSOFROLE { get; set; }
        public virtual DbSet<REFRESHTOKEN> REFRESHTOKEN { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<USERCLAIM> USERCLAIM { get; set; }
        public virtual DbSet<USERLOGIN> USERLOGIN { get; set; }
        public virtual DbSet<USERPROFILE> USERPROFILE { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<USERSINROLE> USERSINROLE { get; set; }
        public virtual DbSet<LOGS> LOGS { get; set; }
    }
}
