//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS
    {
        public System.Guid LOGID { get; set; }
        public string CATEGORY { get; set; }
        public string APPLICATIONNAME { get; set; }
        public string APPLICATIONVERSION { get; set; }
        public string COMPUTERNAME { get; set; }
        public string ACTOR { get; set; }
        public string ACTION { get; set; }
        public string MESSAGE { get; set; }
        public string TRACE { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
    }
}
