//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSIONSOFROLE
    {
        public System.Guid ROLEPERMISSIONID { get; set; }
        public System.Guid ROLEID { get; set; }
        public System.Guid PERMISSIONID { get; set; }
    
        public virtual PERMISSIONS PERMISSIONS { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
