//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFRESHTOKEN
    {
        public System.Guid TOKENID { get; set; }
        public System.Guid APPLICATIONID { get; set; }
        public string SUBJECT { get; set; }
        public System.DateTime UTCCREATED { get; set; }
        public System.DateTime UTCEXPIRY { get; set; }
        public string TICKET { get; set; }
    
        public virtual APPLICATIONS APPLICATIONS { get; set; }
    }
}
