//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.USERCLAIM = new HashSet<USERCLAIM>();
            this.USERLOGIN = new HashSet<USERLOGIN>();
            this.USERSINROLE = new HashSet<USERSINROLE>();
        }
    
        public System.Guid USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERFULLNAME { get; set; }
        public string USEREMAIL { get; set; }
        public string PASSWORD { get; set; }
        public int PASSWORDFAILCOUNT { get; set; }
        public int PASSWORDFORMAT { get; set; }
        public string PASSWORDSALT { get; set; }
        public bool ISAPPROVED { get; set; }
        public bool ISLOCKEDOUT { get; set; }
        public bool ISDELETED { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public Nullable<System.DateTime> DATECHANGEPASS { get; set; }
        public Nullable<System.DateTime> DATELASTACTIVITY { get; set; }
        public Nullable<System.DateTime> DATELASTLOGIN { get; set; }
        public Nullable<System.DateTime> DATELASTLOCKOUT { get; set; }
        public System.Guid DEPARTMENT { get; set; }
        public Nullable<System.DateTime> DATEACCESSEXPIRY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERCLAIM> USERCLAIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERLOGIN> USERLOGIN { get; set; }
        public virtual USERPROFILE USERPROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERSINROLE> USERSINROLE { get; set; }
    }
}
