//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERCLAIM
    {
        public System.Guid CLAIMID { get; set; }
        public System.Guid USERACCOUNTID { get; set; }
        public string TYPE { get; set; }
        public string VALUE { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
