//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSINROLE
    {
        public System.Guid USERINROLEID { get; set; }
        public System.Guid USERID { get; set; }
        public System.Guid ROLEID { get; set; }
    
        public virtual ROLES ROLES { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
